language: android
jdk:
    - oraclejdk8
sudo: false
android:
    components:
        - tools
        - build-tools-26.0.2
        - android-26
        - extra-android-m2repository
script:
    - cd Pdf417MobiSample
    - ./gradlew clean assembleRelease